# Generated by Django 5.0.6 on 2024-09-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_blog_cover_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="catagory",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="publish",
            field=models.BooleanField(default=False),
        ),
    ]
